image: node:latest

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SERVER_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - install
  # - test
  - build
  - deploy_staging
  - deploy_production

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

# test:
#   stage: test
#   script:
#     - npm test
#   artifacts:
#     paths:
#       - node_modules/

build:
  stage: build
  script:
    - npm run build

deploy_staging:
  stage: deploy_staging
  only:
    - staging
  script:
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "
        cd ${SERVER_PATH_STAGING}
        && rm -rf node_modules dist/* tmp
      "
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "
        cd ${SERVER_PATH_STAGING}
        && git pull origin staging
      "
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "
        source ~/.bash_profile
        && export NPM_TOKEN=${NPM_TOKEN}
        && cd ${SERVER_PATH_STAGING}
        && nvm use --delete-prefix
        && git checkout staging
        && npm ci --verbose
        && npm run build
        && npm run copy:sql
      "
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "
        cd ${SERVER_PATH_STAGING}
        && pm2 delete api-staging.urligram.com
      "
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "
        cd ${SERVER_PATH_STAGING}
        && export EMAIL_PASSWORD=${EMAIL_PASSWORD}
        && export DATABASE_PASSWORD=${DATABASE_PASSWORD_STAGING}
        && export JWT_SECRET=${JWT_SECRET}
        && NODE_ENV=staging pm2 start ./dist/src/infrastructure/http/http.js --name api-staging.urligram.com --update-env
      "

deploy_production:
  stage: deploy_production
  only:
    - master
  script:
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "
        cd ${SERVER_PATH_PRODUCTION}
        && rm -rf node_modules dist/* tmp
      "
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "
        cd ${SERVER_PATH_PRODUCTION}
        && git pull origin master
      "
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "
        source ~/.bash_profile
        && export NPM_TOKEN=${NPM_TOKEN}
        && cd ${SERVER_PATH_PRODUCTION}
        && nvm use --delete-prefix
        && git checkout master
        && npm ci --verbose
        && npm run build
        && npm run copy:sql
      "
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "
        cd ${SERVER_PATH_PRODUCTION}
        && pm2 delete api.urligram.com
      "
    - ssh ${SERVER_USER}@${SERVER_ADDRESS} "
        cd ${SERVER_PATH_PRODUCTION}
        && export EMAIL_PASSWORD=${EMAIL_PASSWORD}
        && export DATABASE_PASSWORD=${DATABASE_PASSWORD_PRODUCTION}
        && export JWT_SECRET=${JWT_SECRET}
        && NODE_ENV=production pm2 start ./dist/src/infrastructure/http/http.js --name api.urligram.com --update-env
      "
